/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyName {
    'first': string;
    'last': string;
  }
  interface MyNameAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
    'onValueChanged'?: (event: CustomEvent) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyName': Components.MyName;
  }

  interface StencilIntrinsicElements {
    'my-name': Components.MyNameAttributes;
  }


  interface HTMLMyNameElement extends Components.MyName, HTMLStencilElement {}
  var HTMLMyNameElement: {
    prototype: HTMLMyNameElement;
    new (): HTMLMyNameElement;
  };

  interface HTMLElementTagNameMap {
    'my-name': HTMLMyNameElement
  }

  interface ElementTagNameMap {
    'my-name': HTMLMyNameElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
